// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quan_Ly_Nhan_Su.Data;

#nullable disable

namespace Quan_Ly_Nhan_Su.Migrations
{
    [DbContext(typeof(QLNSDataContext))]
    [Migration("20260330155248_UpdateDuAn")]
    partial class UpdateDuAn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.BangLuong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("KhauTru")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<decimal>("PhuCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThangNam")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Thuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("BangLuong");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.ChamCong", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("GioTangCa")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.DuAn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaTriHopDong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThucDuKien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThucThucTe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiQuanLyID")
                        .HasColumnType("int");

                    b.Property<int?>("PhongBanID")
                        .HasColumnType("int");

                    b.Property<string>("TenDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVienQL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TienDo")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("NguoiQuanLyID");

                    b.HasIndex("PhongBanID");

                    b.ToTable("DuAn");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.NghiPhep", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DenNgay")
                        .HasColumnType("datetime2");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TuNgay")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("NghiPhep");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhongBanID")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PhongBanID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.PhanCongDuAn", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DuAnID")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DuAnID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("PhanCongDuAn");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.PhongBan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhongBan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.TaiKhoan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.BangLuong", b =>
                {
                    b.HasOne("Quan_Ly_Nhan_Su.Data.NhanVien", "NhanVien")
                        .WithMany("BangLuong")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.ChamCong", b =>
                {
                    b.HasOne("Quan_Ly_Nhan_Su.Data.NhanVien", "NhanVien")
                        .WithMany("ChamCong")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.DuAn", b =>
                {
                    b.HasOne("Quan_Ly_Nhan_Su.Data.NhanVien", "NguoiQuanLy")
                        .WithMany()
                        .HasForeignKey("NguoiQuanLyID");

                    b.HasOne("Quan_Ly_Nhan_Su.Data.PhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanID");

                    b.Navigation("NguoiQuanLy");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.NghiPhep", b =>
                {
                    b.HasOne("Quan_Ly_Nhan_Su.Data.NhanVien", "NhanVien")
                        .WithMany("NghiPhep")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.NhanVien", b =>
                {
                    b.HasOne("Quan_Ly_Nhan_Su.Data.PhongBan", "PhongBan")
                        .WithMany("NhanVien")
                        .HasForeignKey("PhongBanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.PhanCongDuAn", b =>
                {
                    b.HasOne("Quan_Ly_Nhan_Su.Data.DuAn", "DuAn")
                        .WithMany("PhanCongDuAn")
                        .HasForeignKey("DuAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quan_Ly_Nhan_Su.Data.NhanVien", "NhanVien")
                        .WithMany("PhanCongDuAn")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuAn");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.DuAn", b =>
                {
                    b.Navigation("PhanCongDuAn");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.NhanVien", b =>
                {
                    b.Navigation("BangLuong");

                    b.Navigation("ChamCong");

                    b.Navigation("NghiPhep");

                    b.Navigation("PhanCongDuAn");
                });

            modelBuilder.Entity("Quan_Ly_Nhan_Su.Data.PhongBan", b =>
                {
                    b.Navigation("NhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
